#!/bin/bash

# Scripts úteis para desenvolvimento da aplicação

echo "🚀 Scripts disponíveis para desenvolvimento:"
echo ""
echo "1️⃣  npm run dev          - Roda API + Frontend simultâneamente"
echo "2️⃣  npm run dev:api      - Roda apenas a API (porta 3001)"
echo "3️⃣  npm run dev:frontend - Roda apenas o Frontend (porta 3000)"
echo "4️⃣  npm test            - Executa todos os testes"
echo "5️⃣  npm run lint        - Verifica código com ESLint"
echo ""
echo "🔧 Comandos úteis da API:"
echo ""
echo "📋 Listar todos os produtores:"
echo "   curl http://localhost:3001/producers"
echo ""
echo "🔍 Buscar produtor por ID:"
echo "   curl http://localhost:3001/producers/1"
echo ""
echo "➕ Criar novo produtor:"
echo '   curl -X POST http://localhost:3001/producers \'
echo '     -H "Content-Type: application/json" \'
echo '     -d '"'"'{"cpfCnpj":"123.456.789-00","nomeProdutor":"Teste","nomeFazenda":"Fazenda Teste","cidade":"São Paulo","estado":"SP","areaTotalHectares":100,"areaAgricultavelHectares":80,"areaVegetacaoHectares":20,"safras":[],"culturas":[]}'"'"
echo ""
echo "🗑️  Deletar produtor:"
echo "   curl -X DELETE http://localhost:3001/producers/ID"
echo ""
echo "📊 Endpoints disponíveis:"
echo "   • GET    /producers     - Lista todos os produtores"
echo "   • GET    /producers/:id - Busca um produtor específico"
echo "   • POST   /producers     - Cria novo produtor"
echo "   • PUT    /producers/:id - Atualiza produtor existente"
echo "   • DELETE /producers/:id - Remove produtor"
echo ""
echo "🌐 URLs:"
echo "   • Frontend: http://localhost:3000"
echo "   • API:      http://localhost:3001"
echo "   • API Doc:  http://localhost:3001/producers"
echo ""
